version: '3'
services:    
     

  postgresnode:
    image: postgresnode    
    build: ./postgresnode
    container_name: postgresnode
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=truckapp
      - POSTGRES_PASSWORD=truckapp
      - POSTGRES_USER=truck
    networks:
      - pnet
    volumes:
      - ./../data/postgresone/logs/:/opt/postgres/logs
      - ./../data/postgresone/data:/var/lib/postgresql/data
      - ./postgresnode/postgresql.conf:/etc/postgresql/postgresql.conf:rw   
    sysctls:
      - kernel.shmmax=100663296

  truckapp:
    image: truckapp
    build: ./truckapp
    container_name: truckapp
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    links:
      - postgresnode         
    depends_on:
      - postgresnode          
    ports:
      - '8089:8089'   
    networks:
      - pnet
      
  
networks:
  pnet:
    driver: bridge   
    ipam:
      driver: default
